spring:
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      springframework: ERROR