INSERT INTO CUSTOMER_ACCOUNT(ACCOUNT_NUMBER, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE_DATE, CURRENCY_CODE, AVL_BALACE, CUSTOMER_NUMBER ) VALUES(123, 'John', 'Savings', '2018-11-08', 'AUD', 84327.51, '789');
INSERT INTO CUSTOMER_ACCOUNT(ACCOUNT_NUMBER, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE_DATE, CURRENCY_CODE, AVL_BALACE, CUSTOMER_NUMBER ) VALUES(456, 'Dave', 'Savings', '2018-11-08', 'AUD', 84327.51, '333');


INSERT INTO ACCOUNT_TRANSACTION(ID, ACCOUNT_NUMBER, ACCOUNT_NAME, VALUE_DATE, CURRENCY_CODE, DEBIT_AMOUNT, CREDIT_AMOUNT, OPERATION_TYPE, TRANSACTION_DESC ) VALUES(1, 123, 'John', '2018-11-08', 'AUD', 0.0, 8843.51, 'Credit', 'Salary');
INSERT INTO ACCOUNT_TRANSACTION(ID, ACCOUNT_NUMBER, ACCOUNT_NAME, VALUE_DATE, CURRENCY_CODE, DEBIT_AMOUNT, CREDIT_AMOUNT, OPERATION_TYPE, TRANSACTION_DESC ) VALUES(2, 123, 'John', '2018-12-08', 'AUD', 500.0, 0.0, 'Debit', 'Rent');
INSERT INTO ACCOUNT_TRANSACTION(ID, ACCOUNT_NUMBER, ACCOUNT_NAME, VALUE_DATE, CURRENCY_CODE, DEBIT_AMOUNT, CREDIT_AMOUNT, OPERATION_TYPE, TRANSACTION_DESC ) VALUES(3, 456, 'Dave', '2018-12-15', 'AUD', 3.50, 0.0, 'Debit', 'Coffee');


